<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RobotVision.InferenceBench</RootNamespace>
    <AssemblyName>RobotVision.InferenceBench.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" />
    <PackageReference Include="OpenCvSharp4.runtime.win" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RobotVision.Core\RobotVision.Core.csproj" />
  </ItemGroup>

</Project>
