<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JLVisionLib\JLVisionLib.csproj" />
    <ProjectReference Include="..\RobotVision.Core\RobotVision.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\JLVisionLib\Libs\JLVisionCore.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>JLVisionCore.dll</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" />
  </ItemGroup>

</Project>
