<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" />
    <PackageReference Include="OpenCvSharp4.runtime.win" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RobotVision.Core\RobotVision.Core.csproj" />
    <ProjectReference Include="..\RobotVision.Infrastructure\RobotVision.Infrastructure.csproj" />
    <ProjectReference Include="..\RobotVision.Vision\RobotVision.Vision.csproj" />
  </ItemGroup>

</Project>
