var root = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "src", "RobotVision.Wpf"));

(string Old, string New)[] fixes =
[
    ("结果?/", "结果图 /"),
    ("结果图?ROI", "结果图 / ROI"),
    ("首次取?测试", "首次取图 / 测试"),
    ("未检出目?1007", "未检出目标 1007"),
    ("取?标定", "取图/标定"),
    ("结果?ROI", "结果图 / ROI"),
    ("名称（字?数字/_/-", "名称（字母/数字/_/-）"),
    ("PLC 触发?=未分配）", "PLC 触发，0=未分配）"),
    ("本框?2 的配方，不是列表?2 项?=未分配", "本框 #2 的配方，不是列表第 2 项；0=未分配"),
    ("工?Id（可手输", "工位 Id（可手输）"),
    ("TRIGGER ?TCP", "TRIGGER / TCP"),
    ("档案?SHA-256", "档案的 SHA-256"),
    ("返?1017", "返回 1017"),
    ("关键?A", "关键点 A"),
    ("关键?B", "关键点 B"),
    ("阈值分?连通域", "阈值分割连通域"),
    ("开运算?px)", "开运算(px)"),
    ("ToolTip=\"? 关闭", "ToolTip=\"0 关闭"),
    ("最小间?px)", "最小间距(px)"),
    ("最大间?px)", "最大间距(px)"),
    ("卡?凸起", "卡尺凸起"),
    ("返?1019", "返回 1019"),
    ("截成?N", "截成前 N"),
    ("（?±3°）", "（约 ±3°）"),
    ("Text=\"?已示教模\"", "Text=\"✓ 已示教模板\""),
    ("阈?边缘?特征框", "阈值/边缘/特征框"),
    ("会?0.85", "会按 0.85"),
    ("定角?+", "定角 +"),
    ("检?ROI", "检测 ROI"),
    ("绿?检测", "绿色=检测"),
    ("吸?料厚", "吸盘/料厚"),
    ("?示教 = Δ", "− 示教 = Δ"),
    ("点一?Δ?", "点一次累加 Δ"),
    ("生?TRIGGER", "生产 TRIGGER"),
    ("检测区?ROI", "检测区域 ROI"),
    ("左上?X（", "左上角 X（"),
    ("左上?Y（", "左上角 Y（"),
    ("左上?X?~1", "左上角 X，0~1"),
    ("左上?Y?~1", "左上角 Y，0~1"),
    ("宽度?~1", "宽度，0~1"),
    ("高度?~1", "高度，0~1"),
    ("控制?Id", "控制器 Id"),
    ("保?测试触发", "保证测试触发"),
    ("（ms? = 永久", "（ms，0 = 永久）"),
    ("可点?0天」", "可设 30 天」"),
    ("backlog?~1024", "backlog，默认 ~1024"),
    ("排队?accept", "排队待 accept"),
    ("上限? = 不限", "上限，0 = 不限"),
    ("直?CPU", "直连 CPU"),
    ("上限? = 不限制）", "上限，0 = 不限制）"),
    ("校验?012/1014", "校验（1012/1014）"),
    ("数量? = 不按数量", "数量，0 = 不按数量"),
    ("保留? = 不按天", "保留，0 = 不按天"),
    ("仅产?TRIGGER", "仅产线 TRIGGER"),
    ("不入库?007", "不入库；1007"),
    ("须勾?SQLite", "须勾选 SQLite"),
    ("次数? = 不联锁）", "次数，0 = 不联锁）"),
    ("TSV? = 不按天", "TSV，0 = 不按天"),
    ("PLC ?CLEARINHIBIT", "PLC 发 CLEARINHIBIT"),
    ("错误?001/1004", "错误（1001/1004"),
    ("；?= 允许所有", "；空 = 允许所有"),
    ("通配?192.168", "通配如 192.168"),
    ("合?IP", "合法 IP"),
    ("?= 保存后生", "⚡ = 保存后生效"),
    ("折叠分?+", "折叠分组 +"),
    ("?运行 / ?未启", "● 运行 / ○ 未启动"),
    ("外包一?DynamicScrollViewer?", "外包一层 DynamicScrollViewer；"),
    ("滚轮链式传递?", "滚轮链式传递；"),
    ("不要?Disabled", "不要用 Disabled"),
    ("逐页修改?====", "逐页修改）===="),
    ("未覆?DataGrid", "未覆盖 DataGrid"),
    ("实时预?/", "实时预览 /"),
    ("字?数字/_/-", "字母/数字/_/-"),
    ("字段?EditType", "字段随 EditType"),
    ("（ms? = 不限速）", "（ms，0 = 不限速）"),
    ("已枚举?Basler", "已枚举的 Basler"),
    ("留?不下发", "留空则不下发"),
    ("设置中?TRIGGER", "设置中的 TRIGGER"),
    ("棋盘?圆点", "棋盘/圆点"),
    ("标准?σ?", "标准差 σ；0"),
    ("默?15×11", "默认 15×11"),
    ("json ?Cameras", "json 的 Cameras"),
    ("合适后?quot;填入编辑?quot;", "合适后「填入编辑区」"),
    ("再?quot;保存&quot;", "再「保存」"),
    ("推理状?结果", "推理状态 / 结果"),
    ("检?分类", "检测/分类"),
    ("经配?相机", "经过配方/相机"),
    ("所?bmp", "所有 bmp"),
    ("上一?下一张", "上一张/下一张"),
    ("迷你卡? 个", "迷你卡片（4 个"),
    ("进?VisionService", "进入 VisionService"),
    ("错误?001", "错误如 1001"),
    ("历史」出?ERR", "历史」出现 ERR"),
    (" · 最?\"", " · 最近 \""),
    ("最近触?\"", "最近触发 \""),
    ("替?DataGrid", "替代 DataGrid"),
    ("最? ", "最近 "),
    ("按配?/", "按配方 /"),
    ("?WebView2", "用 WebView2"),
    ("图像主?+", "图像主区 +"),
    ("点选取?", "点选角点 ·"),
    ("眼在?/", "眼在手 /"),
    ("TCP ?RZ", "TCP 与 RZ"),
    ("拍照?TCP", "拍照点 TCP"),
    ("拍照?RZ ?°)", "拍照点 RZ (°)"),
    ("基坐标?/", "基坐标 /"),
    ("说?+", "说明 +"),
    ("首角点，?棋盘", "首角点，沿棋盘"),
    ("工件平面 ?取图", "工件平面 → 取图"),
    ("示教流?+", "示教流程 +"),
    ("?4 轴每", "第 4 轴每"),
    ("建?5~9", "建议 5~9"),
    ("点表填 ? 个", "点表填 ≥ 3 个"),
    ("零件??δ", "零件角 − δ"),
    ("点?? 个", "点 ≥ 3 个"),
    ("外?旋转中心", "外参/旋转中心"),
    ("Header=\"?轴角\"", "Header=\"第4轴角\""),
    ("启动时?data", "启动时从 data"),
    ("三类档?TabControl", "三类档案 TabControl"),
    ("最大残?\"", "最大残差\""),
    ("分辨?\"", "分辨率\""),
    ("浮动面?428px", "浮动面板 428px"),
    ("像素 ?毫米", "像素 → 毫米"),
    ("比?(mm/px)", "比例 (mm/px)"),
    ("配?外参", "配方外参"),
    ("物?mm", "物长 (mm)"),
    ("Content=\"?X\"", "Content=\"→X\""),
    ("Content=\"?Y\"", "Content=\"→Y\""),
    ("确?ResultLog", "确认 ResultLog"),
    ("视觉系?·", "视觉系统 ·"),
    ("）?相机", "）· 相机"),
    ("实时预?·", "实时预览 ·"),
    ("去畸?·", "去畸变 ·"),
    ("外接矩?双模型", "外接矩形 / 双模型"),
    ("中心连?关键", "中心连线 / 关键"),
    ("中心补?·", "中心补偿 ·"),
    ("?UI 与", "本 UI 与"),
    ("触发?#10;", "触发。&#10;"),
    ("避?TypographyOverrides 自引?BasedOn", "避免 TypographyOverrides 自引用 BasedOn"),
    ("?WPF-UI DefaultComboBox 上只改前?底板，保?Fluent 模板与下拉铬", "在 WPF-UI DefaultComboBox 上只改前景底板，保留 Fluent 模板与下拉样式"),
    ("结果图视\"", "结果图视图\""),
    ("位姿叠加结\"", "位姿叠加结果\""),
    ("Header=\"推理与角\"", "Header=\"推理与角度\""),
    ("匹配阈\"", "匹配阈值\""),
    ("固定阈\"", "固定阈值\""),
    ("Otsu 自动阈\"", "Otsu 自动阈值\""),
    ("框选特\"", "框选特征\""),
    ("记下本次为示教输\"", "记下本次为示教输出\""),
    ("用结果库合格均值建议补\"", "用结果库合格均值建议补偿\""),
    ("Header=\"检测区域（ROI\"", "Header=\"检测区域（ROI）\""),
    ("启用（取图前点亮\"", "启用（取图前点亮）\""),
    ("Text=\"控制\" Margin=\"0,0,0,4\" FontSize=\"11\" />", "Text=\"控制器\" Margin=\"0,0,0,4\" FontSize=\"11\" />"),
    ("通道（≥1\"", "通道（≥1）\""),
    ("精修失败时回退粗角（无方向，不推荐\"", "精修失败时回退粗角（无方向，不推荐）\""),
    ("边缘图定角（更准\"", "边缘图定角（更准）\""),
    ("主模型（.onnx\"", "主模型（.onnx）\""),
    ("次模型（B 特征 .onnx\"", "次模型（B 特征 .onnx）\""),
    ("按名称或备注过滤（F5 刷新\"", "按名称或备注过滤（F5 刷新）\""),
    ("Text=\"\" FontSize=\"9\" Foreground=\"Black\"", "Text=\"停\" FontSize=\"9\" Foreground=\"Black\""),
    ("光照稳定时建议固定阈值更\"", "光照稳定时建议固定阈值更稳\""),
    ("框选区\"", "框选区域\""),
    ("Text=\"拍照位姿校验（OnArm\"", "Text=\"拍照位姿校验（OnArm）\""),
    // Phase 2: truncated strings and remaining ? placeholders
    ("按天保留? = 不清理）", "按天保留，0 = 不清理）"),
    ("不经过配?相机", "不经过配方/相机"),
    ("取图 ?直接", "取图 → 直接"),
    ("?4 轴零位", "第 4 轴零位"),
    ("Text=\"服务状\"", "Text=\"服务状态\""),
    ("Text=\"保存后生\"", "Text=\"保存后生效\""),
    ("Text=\"单次 TRIGGER 总超时（ms\"", "Text=\"单次 TRIGGER 总超时（ms）\""),
    ("Text=\"XY 容差（mm\"", "Text=\"XY 容差（mm）\""),
    ("Content=\"打开失败图目\"", "Content=\"打开失败图目录\""),
    ("Content=\"打开成功图目\"", "Content=\"打开成功图目录\""),
    ("Text=\"缩图最大宽度（0 = 原图\"", "Text=\"缩图最大宽度（0 = 原图）\""),
    ("Text=\"IP 白名\"", "Text=\"IP 白名单\""),
    ("Content=\"启用检测结果留\"", "Content=\"启用检测结果留存\""),
    ("Content=\"写入 SQLite（结果分析页查询\"", "Content=\"写入 SQLite（结果分析页查询）\""),
    ("Content=\"启用文件日志（logs 目录按天滚动\"", "Content=\"启用文件日志（logs 目录按天滚动）\""),
    ("Content=\"启用统计落盘（data/metrics\"", "Content=\"启用统计落盘（data/metrics）\""),
    ("Content=\"达到次数后禁止触发（1018\"", "Content=\"达到次数后禁止触发（1018）\""),
    ("Content=\"保存并应\"", "Content=\"保存并应用\""),
    ("Text=\"总触\"", "Text=\"总触发\""),
    ("Text=\"置信度阈\"", "Text=\"置信度阈值\""),
    ("Text=\"IoU 阈\"", "Text=\"IoU 阈值\""),
    ("各张结\"", "各张结果\""),
    ("掩码置信\"", "掩码置信度\""),
    ("<!-- 推理与角\"-->", "<!-- 推理与角度 -->"),
    ("Content=\"取一\"", "Content=\"取一张\""),
    ("Content=\"应用并取图预\"", "Content=\"应用并取图预览\""),
    ("随时可?-->", "随时可见 -->"),
    ("操作工按画面像素?-->", "操作工按画面像素调整 -->"),
    ("结果图视?-->", "结果图视图 -->"),
    ("语义\"-->", "语义） -->"),
    ("避免重复\"-->", "避免重复） -->"),
    ("不留空\"-->", "不留空） -->"),
    ("关键点模\"-->", "关键点模式 -->"),
    ("双模型模\"-->", "双模型模式 -->"),
    ("无需模型\"-->", "无需模型） -->"),
    ("选择参与标定的相\"", "选择参与标定的相机\""),
    ("与配方外参同名的工位标\"", "与配方外参同名的工位标定\""),
    ("并同步填入宽\"", "并同步填入宽高\""),
    ("已有配方改名后保存：写入新文件并删除旧名（PLC 请改用新名称或序列号\"", "已有配方改名后保存：写入新文件并删除旧名（PLC 请改用新名称或序列号）\""),
    ("Text=\"单帧取图超时（ms\"", "Text=\"单帧取图超时（ms）\""),
    ("Text=\"模拟曝光延时（ms\"", "Text=\"模拟曝光延时（ms）\""),
    ("Content=\"仅读分辨\"", "Content=\"仅读分辨率\""),
    ("Text=\"未注\"", "Text=\"未注册\""),
    ("将批量推\"", "将批量推理\""),
    ("Content=\"开始推\"", "Content=\"开始推理\""),
    ("Content=\"上一\"", "Content=\"上一张\""),
    ("Content=\"下一\"", "Content=\"下一张\""),
    ("字段级标注\"-->", "字段级标注）-->"),
    ("过程能力与连续失败联\"-->", "过程能力与连续失败联锁 -->"),
    ("IP 白名单（默认收起\"-->", "IP 白名单（默认收起）-->"),
    ("（整段通配\"", "（整段通配）\""),
    ("（如 192.168.*\"", "（如 192.168.*）\""),
    ("选中项元数据角标（左上角\"-->", "选中项元数据角标（左上角）-->"),
    ("Content=\"30 \"", "Content=\"30 天\""),
    ("未注册项以琥珀色标\"", "未注册项以琥珀色标识\""),
    ("不另开 GPU\"", "不另开 GPU）\""),
    ("Text=\"合格\" FontSize=\"11\"\n                                           Foreground=\"{DynamicResource TextFillColorTertiaryBrush}\" />\n                                <TextBlock Text=\"{Binding YieldText}\"", "Text=\"合格率\" FontSize=\"11\"\n                                           Foreground=\"{DynamicResource TextFillColorTertiaryBrush}\" />\n                                <TextBlock Text=\"{Binding YieldText}\""),
];

static string NormalizeReplacementChars(string content) =>
    content
        .Replace("\uFFFD?", "?")
        .Replace("\uFFFD", "?");

static string FixTruncatedCommentClosures(string content) =>
    System.Text.RegularExpressions.Regex.Replace(
        content,
        @"<!-- ([^<>\r\n]*?)""-->",
        m => "<!-- " + m.Groups[1].Value + "） -->");

static string FixReplacementCharArtifacts(string content)
{
    if (!content.Contains('?') && !content.Contains('\uFFFD')) return content;

    (string Pattern, string Replacement)[] rules =
    [
        ("未检出目.{0,4}1007", "未检出目标 1007"),
        ("取.{0,3}标定/模型失败则无.{0,3} />", "取图/标定/模型失败则无图\" />"),
        ("（F5 刷新.{0,3} />", "（F5 刷新）\" />"),
        ("Text=\".{0,3} FontSize=\"9\" Foreground=\"Black\"", "Text=\"停\" FontSize=\"9\" Foreground=\"Black\""),
        ("位姿叠加结.{0,3}>", "位姿叠加结果\">"),
        ("名称（字.{0,3}数字/_/-.{0,3} Margin=", "名称（字母/数字/_/-）\" Margin="),
        ("推理与角.{0,3} Margin=", "推理与角度\" Margin="),
        ("主模型（.onnx.{0,3} Margin=", "主模型（.onnx）\" Margin="),
        ("次模型（B 特征 .onnx.{0,3} Margin=", "次模型（B 特征 .onnx）\" Margin="),
        ("掩码置信.{0,3} Margin=", "掩码置信度\" Margin="),
        ("Otsu 自动阈.{0,3} Margin=", "Otsu 自动阈值\" Margin="),
        ("固定阈.{0,3} Margin=", "固定阈值\" Margin="),
        ("控制.{0,3} Margin=", "控制器\" Margin="),
        ("通道（≥1.{0,3} Margin=", "通道（≥1）\" Margin="),
        ("配置工作.{0,3} Margin=", "配置工作台\" Margin="),
        ("详情.{0,3} Padding=", "详情…\" Padding="),
        ("打开配置工作.{0,3} Padding=", "打开配置工作台\" Padding="),
        ("记下本次为示教输.{0,3} Padding=", "记下本次为示教输出\" Padding="),
        ("用结果库合格均值建议补.{0,3} Padding=", "用结果库合格均值建议补偿\" Padding="),
        ("Content=\"取一.{0,3} Command=", "Content=\"取一帧\" Command="),
        ("单帧取图超时（ms.{0,3} Margin=", "单帧取图超时（ms）\" Margin="),
        ("宽（px.{0,3} Margin=", "宽（px）\" Margin="),
        ("高（px.{0,3} Margin=", "高（px）\" Margin="),
        ("模拟曝光延时（ms.{0,3} Margin=", "模拟曝光延时（ms）\" Margin="),
        ("Content=\"仅读分辨.{0,3} Margin=", "Content=\"仅读分辨率\" Margin="),
        (" · 最大残.{0,3} Foreground=", " · 最大残差 \" Foreground="),
        ("分辨.{0,3} Foreground=", "分辨率\" Foreground="),
        ("Text=\"多项.{0,3} />", "Text=\"多项式\" />"),
        ("工.{0,3}Id（可手输.{0,3}", "工位 Id（可手输）\""),
        ("不是列表.{0,3}2 项", "不是列表第 2 项"),
        ("必须保.{0,3} />", "必须保存\" />"),
        ("固定阈值更.{0,3} />", "固定阈值更稳\" />"),
        ("显示可选项.{0,3} />", "显示可选项）\" />"),
        ("补偿后的坐.{0,3} />", "补偿后的坐标\" />"),
        ("再点一次累.{0,3}Δ", "再点一次累加 Δ"),
        ("需要生.{0,3}TRIGGER", "需要生产 TRIGGER"),
        ("试触发不入.{0,3} />", "试触发不入库\" />"),
        ("不改产.{0,3}TRIGGER.{0,3} />", "不改产线 TRIGGER。\" />"),
        ("绿.{0,3}检测", "绿框=检测"),
        ("金.{0,3}匹配窗", "金框=匹配窗"),
        ("保存才上产线.{0,3} />", "保存才上产线。\" />"),
        ("线性比.{0,3}\\(mm/px\\)", "线性比例 (mm/px)"),
        ("即时热加.{0,3} />", "即时热加载\" />"),
        ("同名的工位.{0,3} />", "同名的工位标\" />"),
        ("已改的比例.{0,3}", "已改的比例）\""),
        ("分辨率不.{0,3}", "分辨率不变）\""),
        ("appsettings.json .{0,3}Cameras 节点后重.{0,3} />", "appsettings.json 的 Cameras 节点后重启\" />"),
        ("持久化到配.{0,3} />", "持久化到配置\" />"),
        ("像素 .{0,3}毫米", "像素 → 毫米"),
        ("Header=\"检测区域（ROI.{0,3} IsExpanded", "Header=\"检测区域（ROI）\" IsExpanded"),
        ("启用（取图前点亮.{0,3} FontSize", "启用（取图前点亮）\" FontSize"),
        ("Content=\"框选区.{0,3} FontSize", "Content=\"框选区域\" FontSize"),
        ("启动时.{0,3}data/calibration", "启动时从 data/calibration"),
        ("Content=\"应用并取图预.{0,3} Appearance=", "Content=\"应用并取图预览\" Appearance="),
        ("预\uFFFD? Appearance=", "预览\" Appearance="),
        ("换算助手：物.{0,6}mm ÷ 图上 px = 比例", "换算助手：物长 (mm) ÷ 图上 px = 比例"),
        ("Content=\".{0,3}X\"", "Content=\"→X\""),
        ("Content=\".{0,3}Y\"", "Content=\"→Y\""),
        ("浮动面.{0,6}428px", "浮动面板 428px"),
        ("三类档.{0,6}TabControl", "三类档案 TabControl"),
        ("不刷新主画\"", "不刷新主画面\""),
        ("PLC 触发\\?=未分配", "PLC 触发，0=未分配"),
        ("档案\\?SHA-256", "档案的 SHA-256"),
        ("返\\?1017", "返回 1017"),
        ("关键\\?A", "关键点 A"),
        ("关键\\?B", "关键点 B"),
        ("最小间\\?px\\)", "最小间距(px)"),
        ("最大间\\?px\\)", "最大间距(px)"),
        ("吸\\?料厚", "吸盘/料厚"),
        ("检测区\\?ROI", "检测区域 ROI"),
        ("左上\\?X", "左上角 X"),
        ("左上\\?Y", "左上角 Y"),
        ("宽度\\?~1", "宽度，0~1"),
        ("高度\\?~1", "高度，0~1"),
        ("控制\\?Id", "控制器 Id"),
        ("实时预\\?/", "实时预览 /"),
        ("结果\\?/ ROI", "结果图 / ROI"),
        ("首次取\\?/", "首次取图 /"),
        ("结果图视\\?-->", "结果图视图 -->"),
        ("随时可\\?-->", "随时可见 -->"),
        ("操作工按画面像素\\?-->", "操作工按画面像素调整 -->"),
    ];

    foreach (var (pattern, replacement) in rules)
        content = System.Text.RegularExpressions.Regex.Replace(content, pattern, replacement);
    return content;
}

static string FixWhPx(string content)
{
    if (!content.Contains("?(px)")) return content;
    var parts = content.Split("?(px)");
    var sb = new System.Text.StringBuilder(parts[0]);
  var labels = new[] { "W", "H" };
    for (var i = 1; i < parts.Length; i++)
    {
        sb.Append(labels[(i - 1) % 2]).Append("(px)").Append(parts[i]);
    }
    return sb.ToString();
}

static string FixBytes(string content) =>
    content
        .Replace("<Run Text=\" · ?\" /><Run Text=\"{Binding BytesIn", "<Run Text=\" · 入\" /><Run Text=\"{Binding BytesIn")
        .Replace("<Run Text=\" · ?\" /><Run Text=\"{Binding BytesOut", "<Run Text=\" · 出\" /><Run Text=\"{Binding BytesOut");

static string FixEmptyWh(string content) =>
    content
        .Replace("<TextBlock Text=\"\" Margin=\"0,0,0,4\" FontSize=\"11\" ToolTip=\"宽度，0~1 相对比例\" />",
            "<TextBlock Text=\"W\" Margin=\"0,0,0,4\" FontSize=\"11\" ToolTip=\"宽度，0~1 相对比例\" />")
        .Replace("<TextBlock Text=\"\" Margin=\"0,0,0,4\" FontSize=\"11\" ToolTip=\"高度，0~1 相对比例\" />",
            "<TextBlock Text=\"H\" Margin=\"0,0,0,4\" FontSize=\"11\" ToolTip=\"高度，0~1 相对比例\" />");

var changed = 0;
foreach (var path in Directory.EnumerateFiles(root, "*.xaml", SearchOption.AllDirectories))
{
    var text = File.ReadAllText(path);
    var orig = text;
    text = NormalizeReplacementChars(text);
    foreach (var (old, @new) in fixes)
        text = text.Replace(old, @new);
    text = FixWhPx(text);
    text = FixBytes(text);
    text = FixEmptyWh(text);
    text = FixReplacementCharArtifacts(text);
    text = FixTruncatedCommentClosures(text);
    if (text == orig) continue;
    File.WriteAllText(path, text);
    Console.WriteLine("fixed: " + Path.GetFileName(path));
    changed++;
}

Console.WriteLine("total: " + changed);
